### ISSUE TITLE
Map as-module review

### ISSUE THREAD

**Issue by j8seangel** [GlobalFishingWatch/map-client#1028] opened 2019-04-29 13:07 UTC
This issue collects all the bugs found on the https://github.com/GlobalFishingWatch/map-client/pull/1024 branch, since it has lots of changes and needs a deep test before merging.

- [x] Workspace loads different time ranges on the first load
- [x] Fetch vessel info returns 500 from API and makes the vessel search useless
- [x] Loader spinner not working on layers change
- [x] Heatmap not always rendered on the first load
- [ ] This appeared on the console before the whole browser crashed, not sure if it's related: ![Screenshot 2019-04-29 at 15 01 32](https://user-images.githubusercontent.com/38662877/56898230-cf769200-6a90-11e9-8326-fd9b67706ad8.png)
- [x] Report polygons

**Comment by j8seangel** [comment] 2019-04-29 15:03
> * Workspace loads different time ranges on the first load

@enriquetuya Where can I get the workspace used in .env production to compare?

> * Fetch vessel info returns 500 from API and makes the vessel search useless

Reviewing the request seems that it is using a different endpoint than https://wp-dev.globalfishingwatch.org/map/ 

Instead of [the working one](https://api-dot-skytruth-pleuston.appspot.com/v2/tilesets/gfw-tasks-657-uvi-v2/sub/seriesgroup=1139155/info) it is using https://api-dot-skytruth-pelagos-production.appspot.com/v2/tilesets/gfw-tasks-657-uvi-v2/sub/seriesgroup=1139155/info 500 (see production vs pleuston difference)

@nerik any idea why?

**Comment by nerik** [comment] 2019-04-29 15:30
> @enriquetuya Where can I get the workspace used in .env production to compare?
I'm always using the workspace that goes through the network tab, but there sure is a more elegant solution...

**Comment by enriquetuya** [comment] 2019-05-02 13:02
@j8seangel the default workspace being used is this one in the dev environment: https://wp-dev.globalfishingwatch.org/map/workspace/vizz-default-workspace-v16

**Comment by nerik** [comment] 2019-05-06 09:07
> Fetch vessel info returns 500 from API and makes the vessel search useless

(same issue as reported by @enriquetuya in the google doc). 
I don't understand what's happening here. For the same boat, with the same user account, using the same endpoint, request yields a 500 in this branch and a 200 in production:

![Screenshot 2019-05-06 at 11 05 22](https://user-images.githubusercontent.com/1583415/57216099-27604c00-6fef-11e9-9d85-13cbc38a41f2.png)
![Screenshot 2019-05-06 at 11 05 28](https://user-images.githubusercontent.com/1583415/57216100-27604c00-6fef-11e9-9b0d-b09a022b5486.png)


Any ideas @andres-arana @enriquetuya ?

**Comment by j8seangel** [comment] 2019-05-06 13:45
Workspace is solved, we just need to update the .env variable to use `DEFAULT_WORKSPACE=vizz-default-workspace-v16`

**Comment by andres-arana** [comment] 2019-05-06 18:57
There seems to be a configuration error, maybe on the workspace. The problem is that the `auth`, `me` and `directory` endpoints (basically, everything not related to the workspace) is going for the `https://api-dot-world-fishing-827.appspot.com/v2` server, but tileset loading and other tileset services (search, for example) is going to `https://api-dot-skytruth-pelagos-production.appspot.com/v2`. This causes the access token to be generated for the dev server, and then used on the production server. 

I'll create an issue so that in these situations, the server returns a correct "Unauthorized" response, instead of a 500 error. The problem here is that the token **is** a valid token, since both dev and prod are using the same encryption keys to validate the JWT, however the underlying user doesn't exist in prod. A bit of a convoluted case, but I think we should be using different encryption keys on both envs anyways.

**Comment by nerik** [comment] 2019-05-07 09:07
@andres-arana Thanks for your help. Indeed, there's a discrepancy:
- env's `REACT_APP_V2_API_ENDPOINT` is set to `dot-world-fishing-827`. So generic API requests are done against that (`/me`, etc)
- workspace layers are defined with a `url` set to `dot-skytruth-pelagos-production`. Tiles will be loaded from that server, which works fine, but `/search` and `/info` will fail because those endpoints need auth.

The easy fix is to mirror the production environment and set `REACT_APP_V2_API_ENDPOINT` to `dot-skytruth-pelagos-production`.

Added a note here: https://github.com/GlobalFishingWatch/map-client/issues/871
I think we should remove `url` from workspace layers and let the client build the query to the header using the `tilesetId` field on the workspace + the env `REACT_APP_V2_API_ENDPOINT`
@andres-arana @j8seangel thoughts?

**Comment by enriquetuya** [comment] 2019-05-22 20:25
All the issues seem to be fixed, closing.

**Closed by enriquetuya** 2019-05-22 20:25 UTC
