### ISSUE TITLE
More info about what happens to your data when you upload it

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#689] opened 2017-08-03 10:50 UTC
https://airtable.com/tbliFUBZhHrWTVy5I/viwjB6S36hfjUz7EU/recMc8rL2X3ZD0aaT

**Comment by tiagojsag** [comment] 2017-08-08 16:03
Duplicate of https://github.com/Vizzuality/GlobalFishingWatch/issues/688 ?

**Closed** 2018-07-24 14:49 UTC
Labels: Epic, Workshop proceeding (AirTable), question
